void branch_id(char *str);
void branch_id(char *str)
{
  ;
}

signed int main()
{
  unsigned int main_k;
  unsigned int main_j;
  unsigned int main_i;
  unsigned int main_a;
  unsigned int main_taint;
  main_a = 100u;
  main_i = main_a;
  if (!(main_taint >= 1u))
  {
$0:
*(int*)&&$1;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    main_i = main_i - 1u;
    goto __CPROVER_DUMP_L6;
  }

$1:
*(int*)&&$0;
  main_taint = main_taint - 10u;
  if (main_taint >= 10u)
  {
$1$0:
*(int*)&&$1$1;
    main_j = main_a;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    main_j = main_j - 1u;
    goto __CPROVER_DUMP_L6;
  }

$1$1:
*(int*)&&$1$0;
  __CPROVER_DUMP_L6:
  ;

}

