void branch_id(char *str);
unsigned int uint32_t_secure_load(unsigned int *, void **, unsigned int, unsigned int);
unsigned int a_pub[64] = {905287833u, 1508970235u, 553629498u, 1168305484u, 885136032u, 1282400347u, 1041796878u, 559012531u, 120303990u, 2023087764u, 128139136u, 233532114u, 1304976093u, 799510266u, 408274324u, 488127269u, 245573653u, 2006382166u, 1507943882u, 633609611u, 415637151u, 1783394588u, 811083084u, 2042828222u, 837287382u, 1488009950u, 1145841001u, 1801307942u, 1118613484u, 608611110u, 1583838559u, 530116656u, 295639031u, 165402932u, 1237026040u, 2114565572u, 2009801420u, 1553411181u, 559643451u, 33571197u, 2138238179u, 64493797u, 1056827750u, 1698678578u, 886530892u, 1195833512u, 1660182223u, 2009294236u, 371598759u, 344296817u, 577481493u, 595221715u, 1787761697u, 1280992734u, 520519814u, 728006382u, 809658209u, 482026215u, 1220091186u, 1203382005u, 692551580u, 1424338996u, 317046865u, 1052987150u};
void branch_id(char *str)
{
  ;
}

signed int main()
{
  unsigned int main_i;
  unsigned int main_t;
  unsigned int main_taint;
  unsigned int memop_var_0;
  unsigned int memop_var_1;
  unsigned int memop_var_2;
  unsigned int memop_var_3;
  unsigned int memop_var_4;
  unsigned int memop_var_5;
  unsigned int memop_var_6;
  unsigned int memop_var_7;
  unsigned int memop_var_8;
  unsigned int memop_var_9;
  unsigned int memop_var_10;
  unsigned int memop_var_11;
  unsigned int memop_var_12;
  unsigned int memop_var_13;
  unsigned int memop_var_14;
  unsigned int memop_var_15;
  unsigned int memop_var_16;
  unsigned int memop_var_17;
  unsigned int memop_var_18;
  unsigned int memop_var_19;
  unsigned int memop_var_20;
  unsigned int memop_var_21;
  unsigned int memop_var_22;
  unsigned int memop_var_23;
  unsigned int memop_var_24;
  unsigned int memop_var_25;
  unsigned int memop_var_26;
  unsigned int memop_var_27;
  unsigned int memop_var_28;
  unsigned int memop_var_29;
  unsigned int memop_var_30;
  unsigned int memop_var_31;
  unsigned int memop_var_32;
  unsigned int memop_var_33;
  unsigned int memop_var_34;
  unsigned int memop_var_35;
  unsigned int memop_var_36;
  unsigned int memop_var_37;
  unsigned int memop_var_38;
  unsigned int memop_var_39;
  unsigned int memop_var_40;
  unsigned int memop_var_41;
  unsigned int memop_var_42;
  unsigned int memop_var_43;
  unsigned int memop_var_44;
  unsigned int memop_var_45;
  unsigned int memop_var_46;
  unsigned int memop_var_47;
  unsigned int memop_var_48;
  unsigned int memop_var_49;
  unsigned int memop_var_50;
  unsigned int memop_var_51;
  unsigned int memop_var_52;
  unsigned int memop_var_53;
  unsigned int memop_var_54;
  unsigned int memop_var_55;
  unsigned int memop_var_56;
  unsigned int memop_var_57;
  unsigned int memop_var_58;
  unsigned int memop_var_59;
  unsigned int memop_var_60;
  unsigned int memop_var_61;
  unsigned int memop_var_62;
  unsigned int memop_var_63;
  if (!(main_taint >= 1u))
  {
$0:
*(int*)&&$1;
    main_i = (sizeof(unsigned int [64])) / (sizeof(unsigned int));
    memop_var_0 = uint32_t_secure_load_sensitive_onebase((unsigned int *) (&a_pub[(signed int) main_i]), (char *) a_pub, 0, 2, 0, 0, 256, obsv_ds_bases_size_$0_0, obsv_ds_size_$0_0);
    {
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_1, obsv_ds_bases_size_$1_1, obsv_ds_size_$1_1);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_2, obsv_ds_bases_size_$1_2, obsv_ds_size_$1_2);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_3, obsv_ds_bases_size_$1_3, obsv_ds_size_$1_3);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_4, obsv_ds_bases_size_$1_4, obsv_ds_size_$1_4);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_5, obsv_ds_bases_size_$1_5, obsv_ds_size_$1_5);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_6, obsv_ds_bases_size_$1_6, obsv_ds_size_$1_6);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_7, obsv_ds_bases_size_$1_7, obsv_ds_size_$1_7);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_8, obsv_ds_bases_size_$1_8, obsv_ds_size_$1_8);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_9, obsv_ds_bases_size_$1_9, obsv_ds_size_$1_9);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_10, obsv_ds_bases_size_$1_10, obsv_ds_size_$1_10);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_11, obsv_ds_bases_size_$1_11, obsv_ds_size_$1_11);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_12, obsv_ds_bases_size_$1_12, obsv_ds_size_$1_12);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_13, obsv_ds_bases_size_$1_13, obsv_ds_size_$1_13);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_14, obsv_ds_bases_size_$1_14, obsv_ds_size_$1_14);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_15, obsv_ds_bases_size_$1_15, obsv_ds_size_$1_15);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_16, obsv_ds_bases_size_$1_16, obsv_ds_size_$1_16);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_17, obsv_ds_bases_size_$1_17, obsv_ds_size_$1_17);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_18, obsv_ds_bases_size_$1_18, obsv_ds_size_$1_18);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_19, obsv_ds_bases_size_$1_19, obsv_ds_size_$1_19);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_20, obsv_ds_bases_size_$1_20, obsv_ds_size_$1_20);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_21, obsv_ds_bases_size_$1_21, obsv_ds_size_$1_21);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_22, obsv_ds_bases_size_$1_22, obsv_ds_size_$1_22);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_23, obsv_ds_bases_size_$1_23, obsv_ds_size_$1_23);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_24, obsv_ds_bases_size_$1_24, obsv_ds_size_$1_24);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_25, obsv_ds_bases_size_$1_25, obsv_ds_size_$1_25);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_26, obsv_ds_bases_size_$1_26, obsv_ds_size_$1_26);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_27, obsv_ds_bases_size_$1_27, obsv_ds_size_$1_27);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_28, obsv_ds_bases_size_$1_28, obsv_ds_size_$1_28);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_29, obsv_ds_bases_size_$1_29, obsv_ds_size_$1_29);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_30, obsv_ds_bases_size_$1_30, obsv_ds_size_$1_30);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_31, obsv_ds_bases_size_$1_31, obsv_ds_size_$1_31);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_32, obsv_ds_bases_size_$1_32, obsv_ds_size_$1_32);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_33, obsv_ds_bases_size_$1_33, obsv_ds_size_$1_33);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_34, obsv_ds_bases_size_$1_34, obsv_ds_size_$1_34);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_35, obsv_ds_bases_size_$1_35, obsv_ds_size_$1_35);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_36, obsv_ds_bases_size_$1_36, obsv_ds_size_$1_36);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_37, obsv_ds_bases_size_$1_37, obsv_ds_size_$1_37);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_38, obsv_ds_bases_size_$1_38, obsv_ds_size_$1_38);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_39, obsv_ds_bases_size_$1_39, obsv_ds_size_$1_39);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_40, obsv_ds_bases_size_$1_40, obsv_ds_size_$1_40);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_41, obsv_ds_bases_size_$1_41, obsv_ds_size_$1_41);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_42, obsv_ds_bases_size_$1_42, obsv_ds_size_$1_42);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_43, obsv_ds_bases_size_$1_43, obsv_ds_size_$1_43);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_44, obsv_ds_bases_size_$1_44, obsv_ds_size_$1_44);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_45, obsv_ds_bases_size_$1_45, obsv_ds_size_$1_45);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_46, obsv_ds_bases_size_$1_46, obsv_ds_size_$1_46);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_47, obsv_ds_bases_size_$1_47, obsv_ds_size_$1_47);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_48, obsv_ds_bases_size_$1_48, obsv_ds_size_$1_48);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_49, obsv_ds_bases_size_$1_49, obsv_ds_size_$1_49);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_50, obsv_ds_bases_size_$1_50, obsv_ds_size_$1_50);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_51, obsv_ds_bases_size_$1_51, obsv_ds_size_$1_51);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_52, obsv_ds_bases_size_$1_52, obsv_ds_size_$1_52);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_53, obsv_ds_bases_size_$1_53, obsv_ds_size_$1_53);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_54, obsv_ds_bases_size_$1_54, obsv_ds_size_$1_54);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_55, obsv_ds_bases_size_$1_55, obsv_ds_size_$1_55);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_56, obsv_ds_bases_size_$1_56, obsv_ds_size_$1_56);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_57, obsv_ds_bases_size_$1_57, obsv_ds_size_$1_57);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_58, obsv_ds_bases_size_$1_58, obsv_ds_size_$1_58);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_59, obsv_ds_bases_size_$1_59, obsv_ds_size_$1_59);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_60, obsv_ds_bases_size_$1_60, obsv_ds_size_$1_60);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_61, obsv_ds_bases_size_$1_61, obsv_ds_size_$1_61);
      uint32_t_secure_load_single_sensitive(0, obsv_ds_$1_62, obsv_ds_bases_size_$1_62, obsv_ds_size_$1_62);
    }
    main_t = memop_var_0;
    main_i = main_i - 1u;
    memop_var_1 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_1, obsv_ds_bases_size_$0_1, obsv_ds_size_$0_1);
    main_t = memop_var_1;
    main_i = main_i - 1u;
    memop_var_2 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_2, obsv_ds_bases_size_$0_2, obsv_ds_size_$0_2);
    main_t = memop_var_2;
    main_i = main_i - 1u;
    memop_var_3 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_3, obsv_ds_bases_size_$0_3, obsv_ds_size_$0_3);
    main_t = memop_var_3;
    main_i = main_i - 1u;
    memop_var_4 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_4, obsv_ds_bases_size_$0_4, obsv_ds_size_$0_4);
    main_t = memop_var_4;
    main_i = main_i - 1u;
    memop_var_5 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_5, obsv_ds_bases_size_$0_5, obsv_ds_size_$0_5);
    main_t = memop_var_5;
    main_i = main_i - 1u;
    memop_var_6 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_6, obsv_ds_bases_size_$0_6, obsv_ds_size_$0_6);
    main_t = memop_var_6;
    main_i = main_i - 1u;
    memop_var_7 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_7, obsv_ds_bases_size_$0_7, obsv_ds_size_$0_7);
    main_t = memop_var_7;
    main_i = main_i - 1u;
    memop_var_8 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_8, obsv_ds_bases_size_$0_8, obsv_ds_size_$0_8);
    main_t = memop_var_8;
    main_i = main_i - 1u;
    memop_var_9 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_9, obsv_ds_bases_size_$0_9, obsv_ds_size_$0_9);
    main_t = memop_var_9;
    main_i = main_i - 1u;
    memop_var_10 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_10, obsv_ds_bases_size_$0_10, obsv_ds_size_$0_10);
    main_t = memop_var_10;
    main_i = main_i - 1u;
    memop_var_11 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_11, obsv_ds_bases_size_$0_11, obsv_ds_size_$0_11);
    main_t = memop_var_11;
    main_i = main_i - 1u;
    memop_var_12 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_12, obsv_ds_bases_size_$0_12, obsv_ds_size_$0_12);
    main_t = memop_var_12;
    main_i = main_i - 1u;
    memop_var_13 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_13, obsv_ds_bases_size_$0_13, obsv_ds_size_$0_13);
    main_t = memop_var_13;
    main_i = main_i - 1u;
    memop_var_14 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_14, obsv_ds_bases_size_$0_14, obsv_ds_size_$0_14);
    main_t = memop_var_14;
    main_i = main_i - 1u;
    memop_var_15 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_15, obsv_ds_bases_size_$0_15, obsv_ds_size_$0_15);
    main_t = memop_var_15;
    main_i = main_i - 1u;
    memop_var_16 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_16, obsv_ds_bases_size_$0_16, obsv_ds_size_$0_16);
    main_t = memop_var_16;
    main_i = main_i - 1u;
    memop_var_17 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_17, obsv_ds_bases_size_$0_17, obsv_ds_size_$0_17);
    main_t = memop_var_17;
    main_i = main_i - 1u;
    memop_var_18 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_18, obsv_ds_bases_size_$0_18, obsv_ds_size_$0_18);
    main_t = memop_var_18;
    main_i = main_i - 1u;
    memop_var_19 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_19, obsv_ds_bases_size_$0_19, obsv_ds_size_$0_19);
    main_t = memop_var_19;
    main_i = main_i - 1u;
    memop_var_20 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_20, obsv_ds_bases_size_$0_20, obsv_ds_size_$0_20);
    main_t = memop_var_20;
    main_i = main_i - 1u;
    memop_var_21 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_21, obsv_ds_bases_size_$0_21, obsv_ds_size_$0_21);
    main_t = memop_var_21;
    main_i = main_i - 1u;
    memop_var_22 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_22, obsv_ds_bases_size_$0_22, obsv_ds_size_$0_22);
    main_t = memop_var_22;
    main_i = main_i - 1u;
    memop_var_23 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_23, obsv_ds_bases_size_$0_23, obsv_ds_size_$0_23);
    main_t = memop_var_23;
    main_i = main_i - 1u;
    memop_var_24 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_24, obsv_ds_bases_size_$0_24, obsv_ds_size_$0_24);
    main_t = memop_var_24;
    main_i = main_i - 1u;
    memop_var_25 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_25, obsv_ds_bases_size_$0_25, obsv_ds_size_$0_25);
    main_t = memop_var_25;
    main_i = main_i - 1u;
    memop_var_26 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_26, obsv_ds_bases_size_$0_26, obsv_ds_size_$0_26);
    main_t = memop_var_26;
    main_i = main_i - 1u;
    memop_var_27 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_27, obsv_ds_bases_size_$0_27, obsv_ds_size_$0_27);
    main_t = memop_var_27;
    main_i = main_i - 1u;
    memop_var_28 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_28, obsv_ds_bases_size_$0_28, obsv_ds_size_$0_28);
    main_t = memop_var_28;
    main_i = main_i - 1u;
    memop_var_29 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_29, obsv_ds_bases_size_$0_29, obsv_ds_size_$0_29);
    main_t = memop_var_29;
    main_i = main_i - 1u;
    memop_var_30 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_30, obsv_ds_bases_size_$0_30, obsv_ds_size_$0_30);
    main_t = memop_var_30;
    main_i = main_i - 1u;
    memop_var_31 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_31, obsv_ds_bases_size_$0_31, obsv_ds_size_$0_31);
    main_t = memop_var_31;
    main_i = main_i - 1u;
    memop_var_32 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_32, obsv_ds_bases_size_$0_32, obsv_ds_size_$0_32);
    main_t = memop_var_32;
    main_i = main_i - 1u;
    memop_var_33 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_33, obsv_ds_bases_size_$0_33, obsv_ds_size_$0_33);
    main_t = memop_var_33;
    main_i = main_i - 1u;
    memop_var_34 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_34, obsv_ds_bases_size_$0_34, obsv_ds_size_$0_34);
    main_t = memop_var_34;
    main_i = main_i - 1u;
    memop_var_35 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_35, obsv_ds_bases_size_$0_35, obsv_ds_size_$0_35);
    main_t = memop_var_35;
    main_i = main_i - 1u;
    memop_var_36 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_36, obsv_ds_bases_size_$0_36, obsv_ds_size_$0_36);
    main_t = memop_var_36;
    main_i = main_i - 1u;
    memop_var_37 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_37, obsv_ds_bases_size_$0_37, obsv_ds_size_$0_37);
    main_t = memop_var_37;
    main_i = main_i - 1u;
    memop_var_38 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_38, obsv_ds_bases_size_$0_38, obsv_ds_size_$0_38);
    main_t = memop_var_38;
    main_i = main_i - 1u;
    memop_var_39 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_39, obsv_ds_bases_size_$0_39, obsv_ds_size_$0_39);
    main_t = memop_var_39;
    main_i = main_i - 1u;
    memop_var_40 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_40, obsv_ds_bases_size_$0_40, obsv_ds_size_$0_40);
    main_t = memop_var_40;
    main_i = main_i - 1u;
    memop_var_41 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_41, obsv_ds_bases_size_$0_41, obsv_ds_size_$0_41);
    main_t = memop_var_41;
    main_i = main_i - 1u;
    memop_var_42 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_42, obsv_ds_bases_size_$0_42, obsv_ds_size_$0_42);
    main_t = memop_var_42;
    main_i = main_i - 1u;
    memop_var_43 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_43, obsv_ds_bases_size_$0_43, obsv_ds_size_$0_43);
    main_t = memop_var_43;
    main_i = main_i - 1u;
    memop_var_44 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_44, obsv_ds_bases_size_$0_44, obsv_ds_size_$0_44);
    main_t = memop_var_44;
    main_i = main_i - 1u;
    memop_var_45 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_45, obsv_ds_bases_size_$0_45, obsv_ds_size_$0_45);
    main_t = memop_var_45;
    main_i = main_i - 1u;
    memop_var_46 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_46, obsv_ds_bases_size_$0_46, obsv_ds_size_$0_46);
    main_t = memop_var_46;
    main_i = main_i - 1u;
    memop_var_47 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_47, obsv_ds_bases_size_$0_47, obsv_ds_size_$0_47);
    main_t = memop_var_47;
    main_i = main_i - 1u;
    memop_var_48 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_48, obsv_ds_bases_size_$0_48, obsv_ds_size_$0_48);
    main_t = memop_var_48;
    main_i = main_i - 1u;
    memop_var_49 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_49, obsv_ds_bases_size_$0_49, obsv_ds_size_$0_49);
    main_t = memop_var_49;
    main_i = main_i - 1u;
    memop_var_50 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_50, obsv_ds_bases_size_$0_50, obsv_ds_size_$0_50);
    main_t = memop_var_50;
    main_i = main_i - 1u;
    memop_var_51 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_51, obsv_ds_bases_size_$0_51, obsv_ds_size_$0_51);
    main_t = memop_var_51;
    main_i = main_i - 1u;
    memop_var_52 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_52, obsv_ds_bases_size_$0_52, obsv_ds_size_$0_52);
    main_t = memop_var_52;
    main_i = main_i - 1u;
    memop_var_53 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_53, obsv_ds_bases_size_$0_53, obsv_ds_size_$0_53);
    main_t = memop_var_53;
    main_i = main_i - 1u;
    memop_var_54 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_54, obsv_ds_bases_size_$0_54, obsv_ds_size_$0_54);
    main_t = memop_var_54;
    main_i = main_i - 1u;
    memop_var_55 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_55, obsv_ds_bases_size_$0_55, obsv_ds_size_$0_55);
    main_t = memop_var_55;
    main_i = main_i - 1u;
    memop_var_56 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_56, obsv_ds_bases_size_$0_56, obsv_ds_size_$0_56);
    main_t = memop_var_56;
    main_i = main_i - 1u;
    memop_var_57 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_57, obsv_ds_bases_size_$0_57, obsv_ds_size_$0_57);
    main_t = memop_var_57;
    main_i = main_i - 1u;
    memop_var_58 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_58, obsv_ds_bases_size_$0_58, obsv_ds_size_$0_58);
    main_t = memop_var_58;
    main_i = main_i - 1u;
    memop_var_59 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_59, obsv_ds_bases_size_$0_59, obsv_ds_size_$0_59);
    main_t = memop_var_59;
    main_i = main_i - 1u;
    memop_var_60 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_60, obsv_ds_bases_size_$0_60, obsv_ds_size_$0_60);
    main_t = memop_var_60;
    main_i = main_i - 1u;
    memop_var_61 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_61, obsv_ds_bases_size_$0_61, obsv_ds_size_$0_61);
    main_t = memop_var_61;
    main_i = main_i - 1u;
    memop_var_62 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_62, obsv_ds_bases_size_$0_62, obsv_ds_size_$0_62);
    main_t = memop_var_62;
    main_i = main_i - 1u;
    memop_var_63 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$0_63, obsv_ds_bases_size_$0_63, obsv_ds_size_$0_63);
    main_t = memop_var_63;
    main_i = main_i - 1u;
    goto __CPROVER_DUMP_L3;
  }

$1:
*(int*)&&$0;
  main_i = 0u;
  unsigned int memop_var_64;
  memop_var_64 = uint32_t_secure_load_sensitive_onebase((unsigned int *) (&a_pub[(signed int) main_i]), (char *) a_pub, 0, 2, 0, 0, 256, obsv_ds_bases_size_$1_0, obsv_ds_size_$1_0);
  main_t = memop_var_64 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_65;
  memop_var_65 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_1, obsv_ds_bases_size_$1_1, obsv_ds_size_$1_1);
  main_t = memop_var_65 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_66;
  memop_var_66 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_2, obsv_ds_bases_size_$1_2, obsv_ds_size_$1_2);
  main_t = memop_var_66 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_67;
  memop_var_67 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_3, obsv_ds_bases_size_$1_3, obsv_ds_size_$1_3);
  main_t = memop_var_67 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_68;
  memop_var_68 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_4, obsv_ds_bases_size_$1_4, obsv_ds_size_$1_4);
  main_t = memop_var_68 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_69;
  memop_var_69 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_5, obsv_ds_bases_size_$1_5, obsv_ds_size_$1_5);
  main_t = memop_var_69 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_70;
  memop_var_70 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_6, obsv_ds_bases_size_$1_6, obsv_ds_size_$1_6);
  main_t = memop_var_70 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_71;
  memop_var_71 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_7, obsv_ds_bases_size_$1_7, obsv_ds_size_$1_7);
  main_t = memop_var_71 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_72;
  memop_var_72 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_8, obsv_ds_bases_size_$1_8, obsv_ds_size_$1_8);
  main_t = memop_var_72 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_73;
  memop_var_73 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_9, obsv_ds_bases_size_$1_9, obsv_ds_size_$1_9);
  main_t = memop_var_73 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_74;
  memop_var_74 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_10, obsv_ds_bases_size_$1_10, obsv_ds_size_$1_10);
  main_t = memop_var_74 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_75;
  memop_var_75 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_11, obsv_ds_bases_size_$1_11, obsv_ds_size_$1_11);
  main_t = memop_var_75 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_76;
  memop_var_76 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_12, obsv_ds_bases_size_$1_12, obsv_ds_size_$1_12);
  main_t = memop_var_76 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_77;
  memop_var_77 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_13, obsv_ds_bases_size_$1_13, obsv_ds_size_$1_13);
  main_t = memop_var_77 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_78;
  memop_var_78 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_14, obsv_ds_bases_size_$1_14, obsv_ds_size_$1_14);
  main_t = memop_var_78 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_79;
  memop_var_79 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_15, obsv_ds_bases_size_$1_15, obsv_ds_size_$1_15);
  main_t = memop_var_79 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_80;
  memop_var_80 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_16, obsv_ds_bases_size_$1_16, obsv_ds_size_$1_16);
  main_t = memop_var_80 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_81;
  memop_var_81 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_17, obsv_ds_bases_size_$1_17, obsv_ds_size_$1_17);
  main_t = memop_var_81 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_82;
  memop_var_82 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_18, obsv_ds_bases_size_$1_18, obsv_ds_size_$1_18);
  main_t = memop_var_82 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_83;
  memop_var_83 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_19, obsv_ds_bases_size_$1_19, obsv_ds_size_$1_19);
  main_t = memop_var_83 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_84;
  memop_var_84 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_20, obsv_ds_bases_size_$1_20, obsv_ds_size_$1_20);
  main_t = memop_var_84 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_85;
  memop_var_85 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_21, obsv_ds_bases_size_$1_21, obsv_ds_size_$1_21);
  main_t = memop_var_85 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_86;
  memop_var_86 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_22, obsv_ds_bases_size_$1_22, obsv_ds_size_$1_22);
  main_t = memop_var_86 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_87;
  memop_var_87 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_23, obsv_ds_bases_size_$1_23, obsv_ds_size_$1_23);
  main_t = memop_var_87 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_88;
  memop_var_88 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_24, obsv_ds_bases_size_$1_24, obsv_ds_size_$1_24);
  main_t = memop_var_88 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_89;
  memop_var_89 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_25, obsv_ds_bases_size_$1_25, obsv_ds_size_$1_25);
  main_t = memop_var_89 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_90;
  memop_var_90 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_26, obsv_ds_bases_size_$1_26, obsv_ds_size_$1_26);
  main_t = memop_var_90 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_91;
  memop_var_91 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_27, obsv_ds_bases_size_$1_27, obsv_ds_size_$1_27);
  main_t = memop_var_91 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_92;
  memop_var_92 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_28, obsv_ds_bases_size_$1_28, obsv_ds_size_$1_28);
  main_t = memop_var_92 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_93;
  memop_var_93 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_29, obsv_ds_bases_size_$1_29, obsv_ds_size_$1_29);
  main_t = memop_var_93 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_94;
  memop_var_94 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_30, obsv_ds_bases_size_$1_30, obsv_ds_size_$1_30);
  main_t = memop_var_94 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_95;
  memop_var_95 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_31, obsv_ds_bases_size_$1_31, obsv_ds_size_$1_31);
  main_t = memop_var_95 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_96;
  memop_var_96 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_32, obsv_ds_bases_size_$1_32, obsv_ds_size_$1_32);
  main_t = memop_var_96 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_97;
  memop_var_97 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_33, obsv_ds_bases_size_$1_33, obsv_ds_size_$1_33);
  main_t = memop_var_97 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_98;
  memop_var_98 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_34, obsv_ds_bases_size_$1_34, obsv_ds_size_$1_34);
  main_t = memop_var_98 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_99;
  memop_var_99 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_35, obsv_ds_bases_size_$1_35, obsv_ds_size_$1_35);
  main_t = memop_var_99 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_100;
  memop_var_100 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_36, obsv_ds_bases_size_$1_36, obsv_ds_size_$1_36);
  main_t = memop_var_100 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_101;
  memop_var_101 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_37, obsv_ds_bases_size_$1_37, obsv_ds_size_$1_37);
  main_t = memop_var_101 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_102;
  memop_var_102 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_38, obsv_ds_bases_size_$1_38, obsv_ds_size_$1_38);
  main_t = memop_var_102 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_103;
  memop_var_103 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_39, obsv_ds_bases_size_$1_39, obsv_ds_size_$1_39);
  main_t = memop_var_103 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_104;
  memop_var_104 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_40, obsv_ds_bases_size_$1_40, obsv_ds_size_$1_40);
  main_t = memop_var_104 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_105;
  memop_var_105 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_41, obsv_ds_bases_size_$1_41, obsv_ds_size_$1_41);
  main_t = memop_var_105 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_106;
  memop_var_106 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_42, obsv_ds_bases_size_$1_42, obsv_ds_size_$1_42);
  main_t = memop_var_106 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_107;
  memop_var_107 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_43, obsv_ds_bases_size_$1_43, obsv_ds_size_$1_43);
  main_t = memop_var_107 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_108;
  memop_var_108 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_44, obsv_ds_bases_size_$1_44, obsv_ds_size_$1_44);
  main_t = memop_var_108 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_109;
  memop_var_109 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_45, obsv_ds_bases_size_$1_45, obsv_ds_size_$1_45);
  main_t = memop_var_109 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_110;
  memop_var_110 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_46, obsv_ds_bases_size_$1_46, obsv_ds_size_$1_46);
  main_t = memop_var_110 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_111;
  memop_var_111 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_47, obsv_ds_bases_size_$1_47, obsv_ds_size_$1_47);
  main_t = memop_var_111 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_112;
  memop_var_112 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_48, obsv_ds_bases_size_$1_48, obsv_ds_size_$1_48);
  main_t = memop_var_112 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_113;
  memop_var_113 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_49, obsv_ds_bases_size_$1_49, obsv_ds_size_$1_49);
  main_t = memop_var_113 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_114;
  memop_var_114 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_50, obsv_ds_bases_size_$1_50, obsv_ds_size_$1_50);
  main_t = memop_var_114 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_115;
  memop_var_115 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_51, obsv_ds_bases_size_$1_51, obsv_ds_size_$1_51);
  main_t = memop_var_115 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_116;
  memop_var_116 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_52, obsv_ds_bases_size_$1_52, obsv_ds_size_$1_52);
  main_t = memop_var_116 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_117;
  memop_var_117 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_53, obsv_ds_bases_size_$1_53, obsv_ds_size_$1_53);
  main_t = memop_var_117 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_118;
  memop_var_118 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_54, obsv_ds_bases_size_$1_54, obsv_ds_size_$1_54);
  main_t = memop_var_118 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_119;
  memop_var_119 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_55, obsv_ds_bases_size_$1_55, obsv_ds_size_$1_55);
  main_t = memop_var_119 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_120;
  memop_var_120 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_56, obsv_ds_bases_size_$1_56, obsv_ds_size_$1_56);
  main_t = memop_var_120 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_121;
  memop_var_121 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_57, obsv_ds_bases_size_$1_57, obsv_ds_size_$1_57);
  main_t = memop_var_121 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_122;
  memop_var_122 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_58, obsv_ds_bases_size_$1_58, obsv_ds_size_$1_58);
  main_t = memop_var_122 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_123;
  memop_var_123 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_59, obsv_ds_bases_size_$1_59, obsv_ds_size_$1_59);
  main_t = memop_var_123 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_124;
  memop_var_124 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_60, obsv_ds_bases_size_$1_60, obsv_ds_size_$1_60);
  main_t = memop_var_124 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_125;
  memop_var_125 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_61, obsv_ds_bases_size_$1_61, obsv_ds_size_$1_61);
  main_t = memop_var_125 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_126;
  memop_var_126 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_62, obsv_ds_bases_size_$1_62, obsv_ds_size_$1_62);
  main_t = memop_var_126 / 2u;
  main_i = main_i + 1u;
  unsigned int memop_var_127;
  memop_var_127 = uint32_t_secure_load_single_sensitive((unsigned int *) (&a_pub[(signed int) main_i]), obsv_ds_$1_63, obsv_ds_bases_size_$1_63, obsv_ds_size_$1_63);
  {
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_2, obsv_ds_bases_size_$0_2, obsv_ds_size_$0_2);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_3, obsv_ds_bases_size_$0_3, obsv_ds_size_$0_3);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_4, obsv_ds_bases_size_$0_4, obsv_ds_size_$0_4);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_5, obsv_ds_bases_size_$0_5, obsv_ds_size_$0_5);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_6, obsv_ds_bases_size_$0_6, obsv_ds_size_$0_6);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_7, obsv_ds_bases_size_$0_7, obsv_ds_size_$0_7);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_8, obsv_ds_bases_size_$0_8, obsv_ds_size_$0_8);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_9, obsv_ds_bases_size_$0_9, obsv_ds_size_$0_9);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_10, obsv_ds_bases_size_$0_10, obsv_ds_size_$0_10);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_11, obsv_ds_bases_size_$0_11, obsv_ds_size_$0_11);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_12, obsv_ds_bases_size_$0_12, obsv_ds_size_$0_12);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_13, obsv_ds_bases_size_$0_13, obsv_ds_size_$0_13);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_14, obsv_ds_bases_size_$0_14, obsv_ds_size_$0_14);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_15, obsv_ds_bases_size_$0_15, obsv_ds_size_$0_15);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_16, obsv_ds_bases_size_$0_16, obsv_ds_size_$0_16);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_17, obsv_ds_bases_size_$0_17, obsv_ds_size_$0_17);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_18, obsv_ds_bases_size_$0_18, obsv_ds_size_$0_18);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_19, obsv_ds_bases_size_$0_19, obsv_ds_size_$0_19);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_20, obsv_ds_bases_size_$0_20, obsv_ds_size_$0_20);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_21, obsv_ds_bases_size_$0_21, obsv_ds_size_$0_21);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_22, obsv_ds_bases_size_$0_22, obsv_ds_size_$0_22);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_23, obsv_ds_bases_size_$0_23, obsv_ds_size_$0_23);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_24, obsv_ds_bases_size_$0_24, obsv_ds_size_$0_24);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_25, obsv_ds_bases_size_$0_25, obsv_ds_size_$0_25);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_26, obsv_ds_bases_size_$0_26, obsv_ds_size_$0_26);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_27, obsv_ds_bases_size_$0_27, obsv_ds_size_$0_27);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_28, obsv_ds_bases_size_$0_28, obsv_ds_size_$0_28);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_29, obsv_ds_bases_size_$0_29, obsv_ds_size_$0_29);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_30, obsv_ds_bases_size_$0_30, obsv_ds_size_$0_30);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_31, obsv_ds_bases_size_$0_31, obsv_ds_size_$0_31);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_32, obsv_ds_bases_size_$0_32, obsv_ds_size_$0_32);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_33, obsv_ds_bases_size_$0_33, obsv_ds_size_$0_33);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_34, obsv_ds_bases_size_$0_34, obsv_ds_size_$0_34);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_35, obsv_ds_bases_size_$0_35, obsv_ds_size_$0_35);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_36, obsv_ds_bases_size_$0_36, obsv_ds_size_$0_36);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_37, obsv_ds_bases_size_$0_37, obsv_ds_size_$0_37);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_38, obsv_ds_bases_size_$0_38, obsv_ds_size_$0_38);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_39, obsv_ds_bases_size_$0_39, obsv_ds_size_$0_39);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_40, obsv_ds_bases_size_$0_40, obsv_ds_size_$0_40);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_41, obsv_ds_bases_size_$0_41, obsv_ds_size_$0_41);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_42, obsv_ds_bases_size_$0_42, obsv_ds_size_$0_42);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_43, obsv_ds_bases_size_$0_43, obsv_ds_size_$0_43);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_44, obsv_ds_bases_size_$0_44, obsv_ds_size_$0_44);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_45, obsv_ds_bases_size_$0_45, obsv_ds_size_$0_45);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_46, obsv_ds_bases_size_$0_46, obsv_ds_size_$0_46);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_47, obsv_ds_bases_size_$0_47, obsv_ds_size_$0_47);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_48, obsv_ds_bases_size_$0_48, obsv_ds_size_$0_48);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_49, obsv_ds_bases_size_$0_49, obsv_ds_size_$0_49);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_50, obsv_ds_bases_size_$0_50, obsv_ds_size_$0_50);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_51, obsv_ds_bases_size_$0_51, obsv_ds_size_$0_51);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_52, obsv_ds_bases_size_$0_52, obsv_ds_size_$0_52);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_53, obsv_ds_bases_size_$0_53, obsv_ds_size_$0_53);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_54, obsv_ds_bases_size_$0_54, obsv_ds_size_$0_54);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_55, obsv_ds_bases_size_$0_55, obsv_ds_size_$0_55);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_56, obsv_ds_bases_size_$0_56, obsv_ds_size_$0_56);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_57, obsv_ds_bases_size_$0_57, obsv_ds_size_$0_57);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_58, obsv_ds_bases_size_$0_58, obsv_ds_size_$0_58);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_59, obsv_ds_bases_size_$0_59, obsv_ds_size_$0_59);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_60, obsv_ds_bases_size_$0_60, obsv_ds_size_$0_60);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_61, obsv_ds_bases_size_$0_61, obsv_ds_size_$0_61);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_62, obsv_ds_bases_size_$0_62, obsv_ds_size_$0_62);
    uint32_t_secure_load_single_sensitive(0, obsv_ds_$0_63, obsv_ds_bases_size_$0_63, obsv_ds_size_$0_63);
  }
  main_t = memop_var_127 / 2u;
  main_i = main_i + 1u;
  __CPROVER_DUMP_L3:
  ;

}

